### PR TITLE
Follow Laravel naming standard

### PR DESCRIPTION
**Pull request by hello-liang-shan**

### CODE REVIEW

**Comment by grantholle** [comment]
Ok, seems all right with me. 谢谢大哥

**Comment by grantholle** [comment]
Releasing a new major version (`2.0`) since it's technically a breaking change.

**Comment by hello-liang-shan** [comment]
> Ok, seems all right with me. 谢谢大哥

客气了 老铁 :)

**Comment by grantholle** [comment]
@hello-liang-shan Could you add my 微信？18602661425

**Pull request merged**
